# constants.py

#### Phase1 ####
# video manipulation
FRAMES_PER_SECOND = 30

#### Phase2 ####
# action classification
THRESHOLD_CONFIDENCE = 0.70
TAP_EPSILON = 20
TAP_THRESHOLD = 5
TAP_THRESHOLD2 = 2
SWIPES_THRESHOLD = 100
DISTANCE_MERGE_COMPLEX = 200
LONG_CLICK_THRESHOLD = 2
OPACITY_THRESHOLD = 0.5
SWIPE_EPSILON = 50 # Need to tune more
TAP_COUNT_THRESHOLD = 50
LONG_CLICK_FRAMES = int(LONG_CLICK_THRESHOLD * FRAMES_PER_SECOND / 3)
BEST_FIT_R = 0.75

#### Phase3 ####
# action translation
FRAMES_CONV_FACTOR = 1/FRAMES_PER_SECOND * 1000
WAIT_PER_COMMAND = 0
DELAY_OFFSET = 15.0
# specific codes
DEF_PRESSURE = '00000032'
# general
DIST_THRESHOLD = 31